title = "Learning 24/7..."

baseurl = "/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "&copy;Peter Yuen{year}"

############################
## Advanced options below ##
############################

# Get last modified date for content from Git?
enableGitInfo = false

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = false # Set `true` for Chinese/Japanese/Korean languages.
removePathAccents = true # Workaround for https://github.com/gohugoio/hugo/issues/5687

enableEmoji = true
enableRobotsTXT = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 10 # Number of items per page in paginated lists.
summaryLength = 30 # Listing summary length in words. Also, see `abstract_length` in `params.toml`.

# Workaround Hugo publishing taxonomy URLs as plurals - consistently use singular across Academic.
[permalinks]
authors = "/author/:slug/"
categories = "/category/:slug/"
tags = "/tag/:slug/"

[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]
section = ["HTML", "RSS"]

[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

# Configure the Markdown renderer.
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true # Enable user to embed HTML snippets in Markdown content.
[markup.highlight]
codeFences = false
[markup.tableOfContents]
endLevel = 4
startLevel = 1

[imaging]
anchor = "smart"
quality = 75
resampleFilter = "lanczos"

# Taxonomies.
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

# Related content.
[related]
includeNewer = true
threshold = 80.0
toLower = true

[[related.indices]]
name = "title"
weight = 60.0

[[related.indices]]
name = "summary"
weight = 50.0

[[related.indices]]
name = "tags"
weight = 60.0

[[related.indices]]
name = "categories"
weight = 60.0

[[related.indices]]
name = "series"
weight = 99.0

[[related.indices]]
name = "authors"
weight = 20.0

# Install Wowchemy
[module]
[[module.imports]]
path = "github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5"
[[module.imports]]
path = "github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5"
